# Generated by Django 5.2.7 on 2025-11-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
