# Generated by Django 5.2.7 on 2025-11-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0003_alter_payments_client_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='order',
        ),
    ]
