# Generated by Django 5.2.7 on 2025-11-01 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0010_orders_payment_details'),
        ('Payments', '0004_remove_payments_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.orders'),
        ),
    ]
