# Generated by Django 5.1.4 on 2025-10-31 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discont_percent',
            new_name='discount_percent',
        ),
    ]
