# Generated by Django 5.2.7 on 2025-10-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_rename_discont_percent_product_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Asus Rog', max_length=255),
            preserve_default=False,
        ),
    ]
