# Generated by Django 5.2.8 on 2025-12-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_size_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='spec',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
