# Generated by Django 5.2.8 on 2025-12-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_product_spec'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='review_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
