# Generated by Django 5.2.8 on 2026-01-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_product_rating_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='data',
            new_name='date',
        ),
    ]
