# Generated by Django 5.2.8 on 2026-01-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='variant',
            field=models.CharField(default='danger', max_length=200),
        ),
    ]
