# Generated by Django 5.1.4 on 2025-10-30 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 30, 14, 29, 6, 587043, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
