# Generated by Django 5.1.4 on 2025-10-30 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_users_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='created_at',
        ),
    ]
