# Generated by Django 5.1.4 on 2025-10-31 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_alter_address_options_remove_address_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Auth.address'),
        ),
    ]
