# Generated by Django 5.2.7 on 2025-11-06 14:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0012_remove_address_user_users_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
