# Generated by Django 5.2.7 on 2025-11-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0013_users_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_id',
        ),
    ]
