# Generated by Django 5.2.7 on 2025-11-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0018_alter_users_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='stripe_cutomer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
