# Generated by Django 5.2.7 on 2025-11-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0019_users_stripe_cutomer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='stripe_cutomer_id',
            new_name='stripe_customer_id',
        ),
    ]
