# Generated by Django 5.2.7 on 2025-11-01 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproducts',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
