# Generated by Django 5.2.7 on 2025-11-01 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_rename_qunatity_orderproducts_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='products_details',
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Orders.orders'),
            preserve_default=False,
        ),
    ]
