# Generated by Django 5.2.7 on 2025-11-01 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_rename_create_at_orders_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to='Orders.shippingaddress'),
        ),
    ]
