# Generated by Django 5.2.7 on 2025-11-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_shippingaddress_updated_at_shippingaddress_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproducts',
            options={'verbose_name': 'Ordered Product', 'verbose_name_plural': 'Ordered Products'},
        ),
    ]
