# Generated by Django 5.2.7 on 2025-11-01 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_alter_orderproducts_options'),
        ('Payments', '0004_remove_payments_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_payment_details', to='Payments.payments'),
        ),
    ]
